### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by agarzon** [daveprue/XPlaneImport#8]
There are plans to make this blender 2.8 compatible?.

**Comment by debben** [comment]
I've been looking for a way to import x-plane OBJs into Blender and stumbled upon this repository. I took a stab at getting the plugin to work with 2.80 https://github.com/debben/XPlaneImport/tree/update_2.80

**Comment by agarzon** [comment]
Dude, well done... Just tested and it works. 

I'm not fully sure yet if imports animation and materials properly, but the object, UV map and textures are there and that is incredible helpful.

Thank you.

![Untitled](https://user-images.githubusercontent.com/339828/74613542-50b11b00-50dd-11ea-9f57-bfd7d8f1af03.png)
